apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: failing
spec:
  steps:
    - name: failing-task
      image: nonexistinguser/notavalidcontainer 
      command:
        - echo "hello world"