apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: who
      type: string
  steps:
    - name: teste
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - "/bin/bash"
        - -c
        - echo "Hello $(params.who)"
    